### ISSUE TITLE
Script not working

### ISSUE THREAD

**Issue by nicolaibaralmueller** [cajeeper/PowerCLI#1]
Using latest PowerCli version on vcenter 5.5

![image](https://user-images.githubusercontent.com/33453919/41766519-90320c06-7607-11e8-847b-a3e020646388.png)

![image](https://user-images.githubusercontent.com/33453919/41766614-c9c1e66c-7607-11e8-9853-7f718cdeb711.png)

![image](https://user-images.githubusercontent.com/33453919/41766382-2126822e-7607-11e8-9b15-07cb898f0db1.png)

vSphere Client shows that the script also tried to execute stuff with my domain account although it is never used in the script.

**Comment by cajeeper** [comment]
Sorry, I don't have the means to test vSphere 5.5. Was written and tested with vSphere 6.0.
